# Generated from proto/ws.proto — do not edit by hand.
# Regenerate: .venv/bin/python -m grpc_tools.protoc -Ilovensepy/services/http_api/proto --python_out=lovensepy/services/http_api lovensepy/services/http_api/proto/ws.proto
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ws.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ws.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ws.proto\x12\x0clovensepy.ws\"f\n\x05Hello\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x14\n\x0cinterval_sec\x18\x02 \x01(\x01\x12\x15\n\rheartbeat_sec\x18\x03 \x01(\x01\x12\x11\n\tclient_id\x18\x04 \x01(\t\x12\x0c\n\x04role\x18\x05 \x01(\t\"\x18\n\tHeartbeat\x12\x0b\n\x03rev\x18\x01 \x01(\x03\"\x17\n\x05\x45rror\x12\x0e\n\x06\x64\x65tail\x18\x01 \x01(\t\"\x15\n\x05State\x12\x0c\n\x04json\x18\x01 \x01(\x0c\"e\n\x04\x45\x63ho\x12\n\n\x02id\x18\x01 \x01(\t\x12\n\n\x02t0\x18\x02 \x01(\x01\x12\x0f\n\x02t1\x18\x03 \x01(\x01H\x00\x88\x01\x01\x12\x0f\n\x07\x66rom_id\x18\x04 \x01(\t\x12\r\n\x05to_id\x18\x05 \x01(\t\x12\r\n\x05reply\x18\x06 \x01(\x08\x42\x05\n\x03_t1\"\x06\n\x04Pong\"\xff\x01\n\rServerMessage\x12$\n\x05hello\x18\x01 \x01(\x0b\x32\x13.lovensepy.ws.HelloH\x00\x12$\n\x05state\x18\x02 \x01(\x0b\x32\x13.lovensepy.ws.StateH\x00\x12,\n\theartbeat\x18\x03 \x01(\x0b\x32\x17.lovensepy.ws.HeartbeatH\x00\x12$\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x13.lovensepy.ws.ErrorH\x00\x12\"\n\x04\x65\x63ho\x18\x05 \x01(\x0b\x32\x12.lovensepy.ws.EchoH\x00\x12\"\n\x04pong\x18\x06 \x01(\x0b\x32\x12.lovensepy.ws.PongH\x00\x42\x06\n\x04\x62ody\"\t\n\x07Refresh\"\x06\n\x04Ping\")\n\x08Presence\x12\x0b\n\x03tab\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63tivity\x18\x02 \x01(\t\"&\n\x03Rtt\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x0e\n\x06rtt_ms\x18\x02 \x01(\x01\"\xd7\x01\n\rClientMessage\x12(\n\x07refresh\x18\x01 \x01(\x0b\x32\x15.lovensepy.ws.RefreshH\x00\x12\"\n\x04ping\x18\x02 \x01(\x0b\x32\x12.lovensepy.ws.PingH\x00\x12*\n\x08presence\x18\x03 \x01(\x0b\x32\x16.lovensepy.ws.PresenceH\x00\x12 \n\x03rtt\x18\x04 \x01(\x0b\x32\x11.lovensepy.ws.RttH\x00\x12\"\n\x04\x65\x63ho\x18\x05 \x01(\x0b\x32\x12.lovensepy.ws.EchoH\x00\x42\x06\n\x04\x62odyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ws_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLO']._serialized_start=26
  _globals['_HELLO']._serialized_end=128
  _globals['_HEARTBEAT']._serialized_start=130
  _globals['_HEARTBEAT']._serialized_end=154
  _globals['_ERROR']._serialized_start=156
  _globals['_ERROR']._serialized_end=179
  _globals['_STATE']._serialized_start=181
  _globals['_STATE']._serialized_end=202
  _globals['_ECHO']._serialized_start=204
  _globals['_ECHO']._serialized_end=305
  _globals['_PONG']._serialized_start=307
  _globals['_PONG']._serialized_end=313
  _globals['_SERVERMESSAGE']._serialized_start=316
  _globals['_SERVERMESSAGE']._serialized_end=571
  _globals['_REFRESH']._serialized_start=573
  _globals['_REFRESH']._serialized_end=582
  _globals['_PING']._serialized_start=584
  _globals['_PING']._serialized_end=590
  _globals['_PRESENCE']._serialized_start=592
  _globals['_PRESENCE']._serialized_end=633
  _globals['_RTT']._serialized_start=635
  _globals['_RTT']._serialized_end=673
  _globals['_CLIENTMESSAGE']._serialized_start=676
  _globals['_CLIENTMESSAGE']._serialized_end=891
# @@protoc_insertion_point(module_scope)
