// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file ws.proto (package lovensepy.ws, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ws.proto.
 */
export const file_ws: GenFile = /*@__PURE__*/
  fileDesc("Cgh3cy5wcm90bxIMbG92ZW5zZXB5LndzImYKBUhlbGxvEg8KB3ZlcnNpb24YASABKAkSFAoMaW50ZXJ2YWxfc2VjGAIgASgBEhUKDWhlYXJ0YmVhdF9zZWMYAyABKAESEQoJY2xpZW50X2lkGAQgASgJEgwKBHJvbGUYBSABKAkiGAoJSGVhcnRiZWF0EgsKA3JldhgBIAEoAyIXCgVFcnJvchIOCgZkZXRhaWwYASABKAkiFQoFU3RhdGUSDAoEanNvbhgBIAEoDCJlCgRFY2hvEgoKAmlkGAEgASgJEgoKAnQwGAIgASgBEg8KAnQxGAMgASgBSACIAQESDwoHZnJvbV9pZBgEIAEoCRINCgV0b19pZBgFIAEoCRINCgVyZXBseRgGIAEoCEIFCgNfdDEiBgoEUG9uZyL/AQoNU2VydmVyTWVzc2FnZRIkCgVoZWxsbxgBIAEoCzITLmxvdmVuc2VweS53cy5IZWxsb0gAEiQKBXN0YXRlGAIgASgLMhMubG92ZW5zZXB5LndzLlN0YXRlSAASLAoJaGVhcnRiZWF0GAMgASgLMhcubG92ZW5zZXB5LndzLkhlYXJ0YmVhdEgAEiQKBWVycm9yGAQgASgLMhMubG92ZW5zZXB5LndzLkVycm9ySAASIgoEZWNobxgFIAEoCzISLmxvdmVuc2VweS53cy5FY2hvSAASIgoEcG9uZxgGIAEoCzISLmxvdmVuc2VweS53cy5Qb25nSABCBgoEYm9keSIJCgdSZWZyZXNoIgYKBFBpbmciKQoIUHJlc2VuY2USCwoDdGFiGAEgASgJEhAKCGFjdGl2aXR5GAIgASgJIiYKA1J0dBIPCgdwZWVyX2lkGAEgASgJEg4KBnJ0dF9tcxgCIAEoASLXAQoNQ2xpZW50TWVzc2FnZRIoCgdyZWZyZXNoGAEgASgLMhUubG92ZW5zZXB5LndzLlJlZnJlc2hIABIiCgRwaW5nGAIgASgLMhIubG92ZW5zZXB5LndzLlBpbmdIABIqCghwcmVzZW5jZRgDIAEoCzIWLmxvdmVuc2VweS53cy5QcmVzZW5jZUgAEiAKA3J0dBgEIAEoCzIRLmxvdmVuc2VweS53cy5SdHRIABIiCgRlY2hvGAUgASgLMhIubG92ZW5zZXB5LndzLkVjaG9IAEIGCgRib2R5YgZwcm90bzM");

/**
 * @generated from message lovensepy.ws.Hello
 */
export type Hello = Message<"lovensepy.ws.Hello"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * @generated from field: double interval_sec = 2;
   */
  intervalSec: number;

  /**
   * @generated from field: double heartbeat_sec = 3;
   */
  heartbeatSec: number;

  /**
   * @generated from field: string client_id = 4;
   */
  clientId: string;

  /**
   * @generated from field: string role = 5;
   */
  role: string;
};

/**
 * Describes the message lovensepy.ws.Hello.
 * Use `create(HelloSchema)` to create a new message.
 */
export const HelloSchema: GenMessage<Hello> = /*@__PURE__*/
  messageDesc(file_ws, 0);

/**
 * @generated from message lovensepy.ws.Heartbeat
 */
export type Heartbeat = Message<"lovensepy.ws.Heartbeat"> & {
  /**
   * @generated from field: int64 rev = 1;
   */
  rev: bigint;
};

/**
 * Describes the message lovensepy.ws.Heartbeat.
 * Use `create(HeartbeatSchema)` to create a new message.
 */
export const HeartbeatSchema: GenMessage<Heartbeat> = /*@__PURE__*/
  messageDesc(file_ws, 1);

/**
 * @generated from message lovensepy.ws.Error
 */
export type Error = Message<"lovensepy.ws.Error"> & {
  /**
   * @generated from field: string detail = 1;
   */
  detail: string;
};

/**
 * Describes the message lovensepy.ws.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_ws, 2);

/**
 * @generated from message lovensepy.ws.State
 */
export type State = Message<"lovensepy.ws.State"> & {
  /**
   * UTF-8 JSON object, identical to the REST ``/state`` body.
   *
   * @generated from field: bytes json = 1;
   */
  json: Uint8Array;
};

/**
 * Describes the message lovensepy.ws.State.
 * Use `create(StateSchema)` to create a new message.
 */
export const StateSchema: GenMessage<State> = /*@__PURE__*/
  messageDesc(file_ws, 3);

/**
 * @generated from message lovensepy.ws.Echo
 */
export type Echo = Message<"lovensepy.ws.Echo"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: double t0 = 2;
   */
  t0: number;

  /**
   * @generated from field: optional double t1 = 3;
   */
  t1?: number | undefined;

  /**
   * @generated from field: string from_id = 4;
   */
  fromId: string;

  /**
   * @generated from field: string to_id = 5;
   */
  toId: string;

  /**
   * @generated from field: bool reply = 6;
   */
  reply: boolean;
};

/**
 * Describes the message lovensepy.ws.Echo.
 * Use `create(EchoSchema)` to create a new message.
 */
export const EchoSchema: GenMessage<Echo> = /*@__PURE__*/
  messageDesc(file_ws, 4);

/**
 * @generated from message lovensepy.ws.Pong
 */
export type Pong = Message<"lovensepy.ws.Pong"> & {
};

/**
 * Describes the message lovensepy.ws.Pong.
 * Use `create(PongSchema)` to create a new message.
 */
export const PongSchema: GenMessage<Pong> = /*@__PURE__*/
  messageDesc(file_ws, 5);

/**
 * @generated from message lovensepy.ws.ServerMessage
 */
export type ServerMessage = Message<"lovensepy.ws.ServerMessage"> & {
  /**
   * @generated from oneof lovensepy.ws.ServerMessage.body
   */
  body: {
    /**
     * @generated from field: lovensepy.ws.Hello hello = 1;
     */
    value: Hello;
    case: "hello";
  } | {
    /**
     * @generated from field: lovensepy.ws.State state = 2;
     */
    value: State;
    case: "state";
  } | {
    /**
     * @generated from field: lovensepy.ws.Heartbeat heartbeat = 3;
     */
    value: Heartbeat;
    case: "heartbeat";
  } | {
    /**
     * @generated from field: lovensepy.ws.Error error = 4;
     */
    value: Error;
    case: "error";
  } | {
    /**
     * @generated from field: lovensepy.ws.Echo echo = 5;
     */
    value: Echo;
    case: "echo";
  } | {
    /**
     * @generated from field: lovensepy.ws.Pong pong = 6;
     */
    value: Pong;
    case: "pong";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message lovensepy.ws.ServerMessage.
 * Use `create(ServerMessageSchema)` to create a new message.
 */
export const ServerMessageSchema: GenMessage<ServerMessage> = /*@__PURE__*/
  messageDesc(file_ws, 6);

/**
 * @generated from message lovensepy.ws.Refresh
 */
export type Refresh = Message<"lovensepy.ws.Refresh"> & {
};

/**
 * Describes the message lovensepy.ws.Refresh.
 * Use `create(RefreshSchema)` to create a new message.
 */
export const RefreshSchema: GenMessage<Refresh> = /*@__PURE__*/
  messageDesc(file_ws, 7);

/**
 * @generated from message lovensepy.ws.Ping
 */
export type Ping = Message<"lovensepy.ws.Ping"> & {
};

/**
 * Describes the message lovensepy.ws.Ping.
 * Use `create(PingSchema)` to create a new message.
 */
export const PingSchema: GenMessage<Ping> = /*@__PURE__*/
  messageDesc(file_ws, 8);

/**
 * @generated from message lovensepy.ws.Presence
 */
export type Presence = Message<"lovensepy.ws.Presence"> & {
  /**
   * @generated from field: string tab = 1;
   */
  tab: string;

  /**
   * @generated from field: string activity = 2;
   */
  activity: string;
};

/**
 * Describes the message lovensepy.ws.Presence.
 * Use `create(PresenceSchema)` to create a new message.
 */
export const PresenceSchema: GenMessage<Presence> = /*@__PURE__*/
  messageDesc(file_ws, 9);

/**
 * @generated from message lovensepy.ws.Rtt
 */
export type Rtt = Message<"lovensepy.ws.Rtt"> & {
  /**
   * @generated from field: string peer_id = 1;
   */
  peerId: string;

  /**
   * @generated from field: double rtt_ms = 2;
   */
  rttMs: number;
};

/**
 * Describes the message lovensepy.ws.Rtt.
 * Use `create(RttSchema)` to create a new message.
 */
export const RttSchema: GenMessage<Rtt> = /*@__PURE__*/
  messageDesc(file_ws, 10);

/**
 * @generated from message lovensepy.ws.ClientMessage
 */
export type ClientMessage = Message<"lovensepy.ws.ClientMessage"> & {
  /**
   * @generated from oneof lovensepy.ws.ClientMessage.body
   */
  body: {
    /**
     * @generated from field: lovensepy.ws.Refresh refresh = 1;
     */
    value: Refresh;
    case: "refresh";
  } | {
    /**
     * @generated from field: lovensepy.ws.Ping ping = 2;
     */
    value: Ping;
    case: "ping";
  } | {
    /**
     * @generated from field: lovensepy.ws.Presence presence = 3;
     */
    value: Presence;
    case: "presence";
  } | {
    /**
     * @generated from field: lovensepy.ws.Rtt rtt = 4;
     */
    value: Rtt;
    case: "rtt";
  } | {
    /**
     * @generated from field: lovensepy.ws.Echo echo = 5;
     */
    value: Echo;
    case: "echo";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message lovensepy.ws.ClientMessage.
 * Use `create(ClientMessageSchema)` to create a new message.
 */
export const ClientMessageSchema: GenMessage<ClientMessage> = /*@__PURE__*/
  messageDesc(file_ws, 11);

